apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        # IMPORTANT: This will be replaced by your CI/CD pipeline
        image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/skillbridge/user-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: USERS_TABLE_NAME
          value: "SkillBridgeUsers"
        - name: AWS_REGION
          value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-internal-nlb
  namespace: default
  annotations:
    # This annotation specifies that we want an internal Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80 # The port the load balancer listens on
      targetPort: 8080 # The port the container listens on

