apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-signaling-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webrtc-signaling-service
  template:
    metadata:
      labels:
        app: webrtc-signaling-service
    spec:
      containers:
      - name: webrtc-signaling-service
        image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/skillbridge/webrtc-signaling-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-signaling-service
  namespace: default
  annotations:
    # This annotation specifies that we want a public-facing Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: webrtc-signaling-service
  ports:
    - protocol: TCP
      port: 80 # The port the load balancer listens on
      targetPort: 8080 # The port the container listens on

